
import "./globals.css";



export const metadata = {
  title: " Ipl website",
  description: "Generated by Robin Jain",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="bg-gray-800"
      >
        {children}
      </body>
    </html>
  );
}
